pryecto_tienda/ofertas/urls.py
from django.urls import path
from . import views 

app_name='ofertas'

urlpatterns = [
    path('', views.index, name='index'),
    
]

pryecto_tienda/productos/urls.py
from django.urls import path
from . import views 

app_name='productos'

urlpatterns = [
    path('', views.index, name='index'),
]

pryecto_tienda/pryecto_tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('ofertas/', include('ofertas.urls')),
    path('', views.index,name='index'), 
]

pryecto_tienda/ofertas/models.py
from django.db import models

# Create your models here.

pryecto_tienda/productos/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.nombre
    
       
                
    

pryecto_tienda/ofertas/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
   return render(request, 'ofertas/index.html')

pryecto_tienda/productos/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def index(request):
    productos = Producto.objects.all()
    return render(request, 'productos/index.html', {'productos': productos})
  
     

pryecto_tienda/pryecto_tienda/views.py
from django.shortcuts import render 

def index(request): 
    return render(request,'index.html') 

pryecto_tienda/ofertas/templates/ofertas/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ofertas</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>OFERTAS</h1>
    <a href="/"> Ir Pagina Productos</a>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

pryecto_tienda/productos/templates/productos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{%  static 'css/styles.css' %}">
    <title>Productos</title>
</head>
<body>
    <h1>Lista de Productos</h1>
    <nav>
        <a href="{% url 'index' %}">Home</a>
        <a href="{% url 'ofertas:index' %}">Ir a Ofertas</a>
    </nav>
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>NOMBRE</th>
                    <th>PRECIO</th>
                    <th>CATEGORIA</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    <tr>
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.precio }}</td>
                        <td>{{ producto.categoria.nombre }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">
                            <h4>No hay productos</h4>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

pryecto_tienda/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PRINCIPAL</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <h1>PAGINA PRINCIPAL</h1>
    </header>
    <nav>
        <a href="{% url 'productos:index' %}"> IR A PRODUCTOS </a>
        
        <a href="{% url 'ofertas:index' %}"> IR A OFERTAS </a>
    </nav>
    <div class="container">
        <button id="show-alert">PRESIONA  AQUI</button>
    </div>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>